Awesome project
mike2611/awesome-books pull request #1
Opened 2021-09-13 21:32 UTC by kensayo

2021-09-13 22:21 UTC, carlos-ssh requested changes
Hi Team, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-09-13 22:21 UTC, carlos-ssh commented on js/file.js
> +  for (let i = 0; i < books.length; i += 1) {
**Your project isn't working well i can't display books.**
- Kindly fix errors displayed on chrome console related to line 21 of this file.

2021-09-13 22:21 UTC, carlos-ssh commented on js/file.js
> +/* eslint-disable */
- Implement a well use of your linter. Try to use the right rule without disable eslint.

2021-09-13 22:21 UTC, carlos-ssh commented on js/README.md
> +![](https://img.shields.io/badge/Microverse-blueviolet)
**Your README file isn't displayed well in your repository. Kindly fix it.**

2021-09-14 00:09 UTC, Davidosky007 commented
## Hi @kensayo @mike2611 👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
## Congratulations! 🎉 
![CR1 GIF](https://user-images.githubusercontent.com/52497246/133172788-6826b2d6-75a4-49be-b30f-13ae80e041cd.gif)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2021-09-14 14:15 UTC, merged